# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch-node-browsers-legacy
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo pip install -U pytest
      - run: sudo pip install -U requests
      - run: 
          name: run tests
          command: |
            py.test $folder --junitxml=TestCases/test-reports/junit.xml

      - store_test_results:
          path: TestCases/test-reports/

      - store_artifacts:
          path: TestCases/test-reports/   


      

          